-- GOD FIRST SAVINGS CLUB - SUPABASE SETUP SQL
-- Run this in your Supabase SQL Editor

-- clean start: drop existing tables (run manually if you want fresh slate)
DROP TABLE IF EXISTS otps;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS members;

-- 1. Members Table
CREATE TABLE members (
  phone TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  location_info TEXT,
  savings DECIMAL DEFAULT 0,
  current_loan DECIMAL DEFAULT 0,
  loan_repayment DECIMAL DEFAULT 0,
  savings_goal DECIMAL DEFAULT 0,
  avatar_url TEXT,
  is_admin INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Transactions Table
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_phone TEXT NOT NULL REFERENCES members(phone),
  amount DECIMAL NOT NULL,
  type TEXT NOT NULL,
  proof_ref TEXT,
  reason TEXT,
  member_savings_at_time DECIMAL,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  status TEXT DEFAULT 'pending'
);

-- Ensure new columns exist for existing tables
ALTER TABLE transactions 
ADD COLUMN IF NOT EXISTS reason TEXT,
ADD COLUMN IF NOT EXISTS member_savings_at_time DECIMAL;

-- in case you are running this file against an existing database,
-- make sure the new columns exist without dropping the whole table
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS proof_ref TEXT;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- fix: add missing columns to existing members table
ALTER TABLE members ADD COLUMN IF NOT EXISTS savings DECIMAL DEFAULT 0;
ALTER TABLE members ADD COLUMN IF NOT EXISTS current_loan DECIMAL DEFAULT 0;
ALTER TABLE members ADD COLUMN IF NOT EXISTS loan_repayment DECIMAL DEFAULT 0;
ALTER TABLE members ADD COLUMN IF NOT EXISTS location_info TEXT;
ALTER TABLE members ADD COLUMN IF NOT EXISTS savings_goal DECIMAL DEFAULT 0;
ALTER TABLE members ADD COLUMN IF NOT EXISTS avatar_url TEXT;

-- Migration: Rename bio to location_info if it exists (for backward compatibility during transition)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='members' AND column_name='bio') THEN
    ALTER TABLE members RENAME COLUMN bio TO location_info;
  END IF;
END $$;

-- 3. OTPs Table
CREATE TABLE IF NOT EXISTS otps (
  phone TEXT PRIMARY KEY,
  code TEXT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Enable Security
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE otps ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- 4. Policies
-- Deny public reading so Anon keys can't scrape database
DROP POLICY IF EXISTS "Deny Public Read" ON members;
CREATE POLICY "Deny Public Read" ON members
FOR SELECT TO anon USING (false);

DROP POLICY IF EXISTS "Deny Public Transactions" ON transactions;
CREATE POLICY "Deny Public Transactions" ON transactions
FOR ALL TO anon USING (false);

-- admin rules (use jwt to avoid self-referential loops)
DROP POLICY IF EXISTS "Admin Manage" ON members;
CREATE POLICY "Admin Manage" ON members
FOR ALL TO authenticated
USING (
  (SELECT is_admin FROM members WHERE phone = auth.jwt() ->> 'phone') = 1
)
WITH CHECK (
  (SELECT is_admin FROM members WHERE phone = auth.jwt() ->> 'phone') = 1
);

-- 5. Seed admin
INSERT INTO members (phone, name, is_admin)
VALUES ('62510193', 'Main Admin', 1)
ON CONFLICT (phone) DO UPDATE
SET is_admin = 1;

-- 6. OTP policies (allow creation/verification without auth)
DROP POLICY IF EXISTS "Enable insert for all" ON otps;
CREATE POLICY "Enable insert for all" ON otps
FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable read for all" ON otps;
CREATE POLICY "Enable read for all" ON otps
FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable delete for all" ON otps;
CREATE POLICY "Enable delete for all" ON otps
FOR DELETE USING (true);

-- 7. Sessions Table (for Express backend persistent sessions)
DROP TABLE IF EXISTS sessions;
CREATE TABLE sessions (
  sid TEXT PRIMARY KEY,
  sess JSON NOT NULL,
  expire TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Deny public read on sessions
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deny Public Sessions" ON sessions;
CREATE POLICY "Deny Public Sessions" ON sessions
FOR ALL TO anon USING (false);

-- 8. Baileys Authentication Table (Persistent WhatsApp Bot)
DROP TABLE IF EXISTS baileys_auth;
CREATE TABLE baileys_auth (
  id TEXT PRIMARY KEY,
  data JSONB NOT NULL
);

-- Deny public read on bot keys
ALTER TABLE baileys_auth ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deny Public Baileys Auth" ON baileys_auth;
CREATE POLICY "Deny Public Baileys Auth" ON baileys_auth
FOR ALL TO anon USING (false);
